import json

import requests

TREE_URL = "https://raw.githubusercontent.com/grindinggear/skilltree-export/refs/heads/master/data.json"
ALT_ASCENDANCIES_FILE = "src/mytypes/alt-ascendancies.ts"

HEADER = """// automatically generated by icon-generation/fetch_alt_ascendancies.py

export const ALT_ASCENDANCIES: string[] = [
"""


def fetch_alt_ascendancy_names() -> list[str]:
    response = requests.get(TREE_URL, headers={"User-Agent": "bpl-data-fetch"})
    response.raise_for_status()
    alternate_ascendancies = response.json()["alternate_ascendancies"]
    return [
        node["name"].split(" Bloodline")[0]
        for node in alternate_ascendancies if node["name"].endswith("Bloodline")
    ]


def main():
    names = fetch_alt_ascendancy_names()

    with open(ALT_ASCENDANCIES_FILE, "w", encoding="utf-8") as f:
        f.write(HEADER)
        for name in names:
            f.write(f"  {json.dumps(name)},\n")
        f.write("];\n")

    print(f"Alt ascendancies: {len(names)} written to {ALT_ASCENDANCIES_FILE}")


if __name__ == "__main__":
    main()
