import json

import requests

TREE_URL = "https://repoe-fork.github.io/passive_skill_trees/DefaultAltAscendancies.json"
ALT_ASCENDANCIES_FILE = "../src/mytypes/alt-ascendancies.ts"

HEADER = """// Sourced from RePoE's DefaultAltAscendancies.json passive tree
// (https://repoe-fork.github.io/passive_skill_trees/DefaultAltAscendancies.json),
// generated by fetch_alt_ascendancies.py - the nodes with
// is_ascendancy_starting_node: true whose id starts with
// "AlternateAscendancy" rather than the normal "Ascendancy" classes.
export const ALT_ASCENDANCIES: string[] = [
"""


def fetch_alt_ascendancy_names() -> list[str]:
    response = requests.get(TREE_URL, headers={"User-Agent": "bpl-data-fetch"})
    response.raise_for_status()
    passives = response.json()["passives"]
    return [
        node["name"]
        for node in passives.values()
        if node.get("is_ascendancy_starting_node")
        and node["id"].startswith("AlternateAscendancy")
    ]


def main():
    names = fetch_alt_ascendancy_names()

    with open(ALT_ASCENDANCIES_FILE, "w", encoding="utf-8") as f:
        f.write(HEADER)
        for name in names:
            f.write(f"  {json.dumps(name)},\n")
        f.write("];\n")

    print(f"Alt ascendancies: {len(names)} written to {ALT_ASCENDANCIES_FILE}")


if __name__ == "__main__":
    main()
