import json
import os
import re

import requests

# ModFoulbornMap.lua is generated by PoB's own build pipeline (see
# mapUniqueToFoulborn.lua upstream) directly from GGG's game data, so it's
# both more complete and more reliably formatted than scraping the wiki's
# hand-maintained "Foulborn_unique_item" wikitable ever was.
MOD_MAP_URL = "https://raw.githubusercontent.com/PathOfBuildingCommunity/PathOfBuilding/dev/src/Data/ModFoulbornMap.lua"
UNIQUES_FILE = "public/assets/poe1/items/uniques.json"
FOULBORN_FILE = "public/assets/poe1/items/foulborn_uniques.json"

ROLL_RE = re.compile(r"([+-]?)\(-?\d+(?:\.\d+)?[-–—]-?\d+(?:\.\d+)?\)(%?)")
ITEM_RE = re.compile(r'^\t\["((?:[^"\\]|\\.)*)"\] = \{$')
MOD_RE = re.compile(r'^\t\t"((?:[^"\\]|\\.)*)",$')


def strip_roll(text: str) -> str:
    # Replace the roll range (e.g. "(50-75)%") with a "#" placeholder,
    # keeping whatever sign/percent sign surrounded it, so "gain (20-25)%
    # of Mana Cost" becomes "gain #% of Mana Cost" instead of leaving a
    # dangling "gain of Mana Cost".
    return ROLL_RE.sub(r"\1#\2", text)


def fetch_foulborn_mod_map_lua() -> str:
    response = requests.get(MOD_MAP_URL, headers={"User-Agent": "bpl-data-fetch"})
    response.raise_for_status()
    return response.text


def parse_foulborn_rows(lua_text: str):
    rows = []
    current_name = None
    for line in lua_text.splitlines():
        item_match = ITEM_RE.match(line)
        if item_match:
            current_name = item_match.group(1)
            continue
        mod_match = MOD_RE.match(line)
        if mod_match and current_name:
            rows.append({
                "name": current_name,
                "mod": strip_roll(mod_match.group(1)),
            })
    return rows


def fetch_foulborn_uniques():
    # Only used to validate that the base unique actually exists - never
    # written to, and base_item/is_drop_restricted are deliberately not
    # copied into the output. Consumers should always resolve those (and
    # the icon) from uniques.json by "name" at render time, so this data
    # can never drift out of sync with it.
    with open(UNIQUES_FILE) as f:
        uniques = json.load(f)

    rows = parse_foulborn_rows(fetch_foulborn_mod_map_lua())

    entries = []
    skipped_missing_base = 0
    seen = set()
    for row in rows:
        if row["name"] not in uniques:
            skipped_missing_base += 1
            continue
        dedupe_key = (row["name"], row["mod"])
        if dedupe_key in seen:
            continue
        seen.add(dedupe_key)
        entries.append({"name": row["name"], "mod": row["mod"]})

    entries.sort(key=lambda e: (e["name"], e["mod"]))

    with open(FOULBORN_FILE, "w") as f:
        f.write(json.dumps(entries, separators=(",", ":")))

    print(f"Foulborn uniques: {len(entries)} written to {FOULBORN_FILE}, {skipped_missing_base} skipped (base item not found)")


if __name__ == "__main__":
    fetch_foulborn_uniques()
