import json

from fetch_wiki_data import request_data_from_wiki

SKILL_GEMS_FILE = "../src/mytypes/skill-gems.ts"
MAIN_SKILL_FILE = "../src/mytypes/main-skill.ts"

COLOR_BY_ATTRIBUTE = {
    "strength": "text-red-500",
    "dexterity": "text-green-500",
    "intelligence": "text-blue-500",
    "none": "text-white",
}

# Gem tags to exclude from the active-skill-gem list. In case we want aura
# gems too, set this to an empty set - I wanted main skill gems only.
EXCLUDE_TAGS = {"Aura"}
# EXCLUDE_TAGS = set()  # uncomment to include aura gems too

# Some non-aura skills (mines, totems, melee strikes, traps) also carry an
# incidental "Aura" tag for a secondary effect they grant (e.g. Smite,
# Icicle Mine, Rejuvenation Totem). Only apply EXCLUDE_TAGS when the gem has
# none of these "real" delivery-mechanism tags, so those stay in.
DELIVERY_TAGS = {"Mine", "Totem", "Trap", "Minion", "Melee", "Attack", "Strike", "Nova"}

SKILL_GEMS_HEADER = """// Active skill gems only (no auras, no support gems), generated by
// fetch_skill_gems.py from poewiki's Cargo `items` table
// (class_id="Active Skill Gem", drop_enabled=1). Transfigured ("of X")
// variants are listed as separate entries from their base gem, since they
// play very differently.
export const SKILL_GEMS: string[] = [
"""

MAIN_SKILL_HEADER = """// Gem colour (primary attribute: strength/dexterity/intelligence =
// red/green/blue, colourless = white), generated by fetch_skill_gems.py from
// poewiki's Cargo `skill_gems` table (primary_attribute field). Kept
// separate from skill-gems.ts (the raw gem list) the same way ascendancy.ts
// keeps colour data next to its own list.
export const SKILL_GEM_COLORS: Record<string, string> = {
"""


def ts_string(value: str) -> str:
    return json.dumps(value)


def ts_key(name: str) -> str:
    # Prettier drops the quotes around object keys that are valid JS
    # identifiers, so match that style for a stable/no-op diff.
    if name.isidentifier():
        return name
    return json.dumps(name)


def fetch_active_gem_names() -> list[str]:
    fields = ["name", "class_id", "drop_enabled"]
    where = "class_id=%22Active%20Skill%20Gem%22"
    data = request_data_from_wiki(["items"], fields, where)
    return sorted({item["name"] for item in data if item["drop_enabled"]})


# Wiki page titles that are disambiguated and don't match the item name.
PAGE_NAME_ALIASES = {
    "Portal": "Portal (skill gem)",
}


def fetch_gem_info() -> dict[str, dict]:
    fields = ["_pageName=name", "primary_attribute", "gem_tags"]
    data = request_data_from_wiki(["skill_gems"], fields)
    info = {
        item["name"]: {
            "primary_attribute": item["primary_attribute"],
            "tags": (item["gem_tags"] or "").split(","),
        }
        for item in data
    }
    for item_name, page_name in PAGE_NAME_ALIASES.items():
        if page_name in info:
            info[item_name] = info[page_name]
    return info


def main():
    names = fetch_active_gem_names()
    gem_info = fetch_gem_info()

    colors: dict[str, str] = {}
    skipped = []
    excluded_by_tag = []
    for name in names:
        info = gem_info.get(name)
        tags = set(info["tags"]) if info else set()
        if EXCLUDE_TAGS & tags and not DELIVERY_TAGS & tags:
            excluded_by_tag.append(name)
            continue
        attribute = info["primary_attribute"] if info else None
        color = COLOR_BY_ATTRIBUTE.get(attribute) if attribute else None
        if color is None:
            skipped.append(name)
            continue
        colors[name] = color
    names = [n for n in names if n not in excluded_by_tag]

    with open(SKILL_GEMS_FILE, "w", encoding="utf-8") as f:
        f.write(SKILL_GEMS_HEADER)
        for name in names:
            f.write(f"  {ts_string(name)},\n")
        f.write("];\n")

    with open(MAIN_SKILL_FILE, "w", encoding="utf-8") as f:
        f.write(MAIN_SKILL_HEADER)
        for name, color in colors.items():
            f.write(f"  {ts_key(name)}: {ts_string(color)},\n")
        f.write("};\n")

    print(
        f"Skill gems: {len(names)} written to {SKILL_GEMS_FILE}, "
        f"{len(colors)} colors written to {MAIN_SKILL_FILE}, "
        f"{len(excluded_by_tag)} excluded by tag ({', '.join(EXCLUDE_TAGS) or 'none'}), "
        f"{len(skipped)} skipped (no primary_attribute found)"
    )
    if skipped:
        print("Skipped:", ", ".join(skipped))


if __name__ == "__main__":
    main()
