import os
from typing import Optional, TypedDict
from urllib import request
import urllib.parse
import json
from build_images import generate_flask_image, generate_gem_image


def encode(string: str) -> str:
    return (
        string
        .replace(" ", "_")
        .replace("%", "")
        .replace(",", "")
        .replace("'", "")
        .replace('"', "")
        .replace(':', "")
    )


class VisualIdentity(TypedDict):
    dds_file: str


class Item(TypedDict):
    name: str
    visual_identity: dict


ItemDict = dict[str, Item]


class Gem(TypedDict):
    display_name: str
    discriminator: Optional[str]
    color: Optional[str]


def get_base_name(gem) -> Optional[str]:
    if "base_item" in gem:
        if gem["base_item"] is not None:
            return gem["base_item"]["display_name"]
    return None


GEMS_TS_FILE = "src/utils/gems.ts"
ALL_GEM_INFO: dict[str, list[dict]] = {}


def is_support_gem(gem: dict) -> bool:
    return bool(gem.get("is_support")) or gem.get("gem_type") == "support"


def is_transfigured_gem(gem: dict, display_name: str) -> bool:
    # poe1 only; the alt_z ("of Trarthus") gems carry no discriminator.
    return gem.get("discriminator") in ("alt_x", "alt_y") or "Trarthus" in display_name


def write_gems_ts(gem_info: dict[str, list[dict]]):
    # Run prettier afterwards.
    with open(GEMS_TS_FILE, "w", encoding="utf-8") as file:
        file.write("// Generated by icon-generation/fetch_icons.py - do not edit.\n")
        file.write("export const gems = ")
        json.dump(gem_info, file, indent=2)
        file.write(";\n")


def get_gem_dict(version: str) -> dict[str, list[Gem]]:
    url = "https://repoe-fork.github.io/gems.min.json"
    if (version == "poe2"):
        url = "https://repoe-fork.github.io/poe2/skill_gems.min.json"
    response = request.urlopen(url)
    full_gems: list = json.loads(response.read()).values()
    gems: dict[str, list[Gem]] = {}
    gem_info: dict[str, dict] = {}
    for gem in full_gems:
        display_name = ""
        if "active_skill" in gem:
            display_name = gem["active_skill"]["display_name"]
        elif "base_item" in gem:
            display_name = gem["base_item"]["display_name"]
        else: 
            continue
        
        if display_name == "" or any(marker in display_name for marker in ("DNT", "DO NOT USE", "UNUSED", "Playtest", "WIP", "...")):
            continue
        base_name = get_base_name(gem)
        if base_name is not None:
            if base_name not in gems:
                gems[base_name] = []
            if "color" in gem and gem["color"] is not None:
                gem_info[display_name] = {
                    "name": display_name,
                    "is_support": is_support_gem(gem),
                    "is_transfigured": is_transfigured_gem(gem, display_name),
                    "color": gem["color"],
                }
            gems[base_name].append({
                "display_name": display_name,
                "discriminator": gem.get("discriminator"),
                "color": gem.get("color")
            })
    ALL_GEM_INFO[version] = sorted(gem_info.values(), key=lambda g: g["name"])
    return gems


def download():
    for version in ["poe1", "poe2"]:
        gems = get_gem_dict(version)
        if not os.path.exists(f"public/assets/{version}/items/uniques"):
            os.makedirs(f"public/assets/{version}/items/uniques")
        if not os.path.exists(f"public/assets/{version}/items/basetypes"):
            os.makedirs(f"public/assets/{version}/items/basetypes")
        if not os.path.exists(f"icon-generation/temp/{version}"):
            os.makedirs(f"icon-generation/temp/{version}")

        baseUrl = "https://repoe-fork.github.io/"
        if version == "poe2":
            baseUrl += "poe2/"
        response = request.urlopen(
            f"{baseUrl}/base_items.min.json")
        base_items: ItemDict = json.loads(response.read())
        save_basetypes(f"public/assets/{version}/items/basetypes.json", base_items)

        response = request.urlopen(
            f"{baseUrl}/uniques.min.json")
        uniques: ItemDict = json.loads(response.read())

        for unique in uniques.values():
            if "[DNT" in unique["name"] or "DO NOT USE" in unique["name"] or "UNUSED" in unique["name"]:
                continue
            save_image(
                unique, f"public/assets/{version}/items/uniques", baseUrl, {})
        for base in base_items.values():
            if "[DNT" in base["name"] or "DO NOT USE" in base["name"] or "UNUSED" in base["name"]:
                continue
            save_image(base, f"public/assets/{version}/items/basetypes", baseUrl, gems if version == "poe1" else {})
    write_gems_ts(ALL_GEM_INFO)


def save_basetypes(filename: str, base_items: ItemDict):
    names = [
        item["name"] for item in base_items.values()
        if item["domain"] != "undefined" and "DO NOT USE" not in item["name"] and "UNUSED" not in item["name"]
    ]
    
    with open(filename, "w") as f:
        json.dump(sorted(names, key=lambda s: len(s), reverse=True), f, separators=(',', ':'))
    

anomalous_uniques = [
    "Sekhema's Resolve",
    "Grand Spectrum",

    "Impresence",
    "Combat Focus",
    "Precursor's Emblem",
    "Doryani's Delusion",
    "The Beachhead",
]


def save_gem_image(base_name, gems: list[Gem], path: str, url: str):
    game_version = "poe1" if "poe1" in path else "poe2"
    temp_path = os.path.join(
        f"icon-generation/temp/{game_version}", encode(base_name) + ".webp")

    if not os.path.isfile(temp_path):
        try:
            response = request.urlopen(url)
            with open(temp_path, "wb") as file:
                file.write(response.read())
        except Exception as e:
            print("could not download", url)
            print(e)
            return
    for gem in gems:
        try:
            discriminator = gem["discriminator"]
            if "Trarthus" in gem["display_name"]:
                discriminator = "alt_z"
            img = generate_gem_image(
                temp_path, gem["color"], discriminator)
            img.save(os.path.join(path, encode(gem["display_name"]) + ".webp"))
        except Exception as e:
            print("could not save", e)


def save_flask_image(item: Item, path: str, baseUrl: str):
    name = item["name"]
    game_version = "poe1" if "poe1" in path else "poe2"
    rarity = "unique" if "unique" in path else "normal"
    temp_path = os.path.join(
        f"icon-generation/temp/{game_version}", encode(name) + ".webp")
    full_path = os.path.join(path, encode(name) + ".webp")
    if not os.path.isfile(temp_path):

        item_path = urllib.parse.quote(
            item["visual_identity"]["dds_file"].replace('.dds', '')) + ".webp"
        url = baseUrl + item_path
        try:
            response = request.urlopen(url)
            with open(temp_path, "wb") as file:
                file.write(response.read())
        except Exception as e:
            print("could not download", url)
            print(e)
            return
    generate_flask_image(temp_path, game_version, rarity).save(full_path)


def save_image(item: Item, path: str, baseUrl: str, gems: dict[str, list[Gem]]):
    name = item["name"]
    if name in anomalous_uniques:
        name = item["visual_identity"]["dds_file"].split(
            "/")[-1].replace(".dds", "")
    elif name in gems:
        return save_gem_image(name, gems[name], path, baseUrl +
                              urllib.parse.quote(item["visual_identity"]["dds_file"].replace('.dds', '')) + ".webp")
    if (item.get("domain") == "flask" and "Charm" not in name) or item.get("item_class") == "Flask":
        return save_flask_image(item, path, baseUrl)

    full_path = os.path.join(path, encode(name) + ".webp")
    if os.path.isfile(full_path):
        return
    item_path = urllib.parse.quote(
        item["visual_identity"]["dds_file"].replace('.dds', '')) + ".webp"
    url = baseUrl + item_path
    try:
        response = request.urlopen(url)
        with open(full_path, "wb") as file:
            file.write(response.read())
    except Exception as e:
        print("could not download", url)


if __name__ == "__main__":
    download()
