/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmissionsRouteImport } from './routes/submissions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as TeamRouteRouteImport } from './routes/team/route'
import { Route as StreamsRouteRouteImport } from './routes/streams/route'
import { Route as ScoresRouteRouteImport } from './routes/scores/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TeamWishlistRouteImport } from './routes/team/wishlist'
import { Route as TeamAtlasRouteImport } from './routes/team/atlas'
import { Route as StreamsTwitchAccountRouteImport } from './routes/streams/$twitchAccount'
import { Route as ScoresUniquesRouteImport } from './routes/scores/uniques'
import { Route as ScoresSlotUniquesRouteImport } from './routes/scores/slot-uniques'
import { Route as ScoresScarabsRouteImport } from './routes/scores/scarabs'
import { Route as ScoresRacesRouteImport } from './routes/scores/races'
import { Route as ScoresProgressRouteImport } from './routes/scores/progress'
import { Route as ScoresLadderRouteImport } from './routes/scores/ladder'
import { Route as ScoresHeistRouteImport } from './routes/scores/heist'
import { Route as ScoresGraftRaceRouteImport } from './routes/scores/graft-race'
import { Route as ScoresGemsRouteImport } from './routes/scores/gems'
import { Route as ScoresFoulbornUniquesRouteImport } from './routes/scores/foulborn-uniques'
import { Route as ScoresForYouRouteImport } from './routes/scores/for-you'
import { Route as ScoresFocusUniquesRouteImport } from './routes/scores/focus-uniques'
import { Route as ScoresDelveRouteImport } from './routes/scores/delve'
import { Route as ScoresDailiesRouteImport } from './routes/scores/dailies'
import { Route as ScoresCollectionsRouteImport } from './routes/scores/collections'
import { Route as ScoresBountiesRouteImport } from './routes/scores/bounties'
import { Route as ScoresBingoRouteImport } from './routes/scores/bingo'
import { Route as ScoresAscendancyChallengesRouteImport } from './routes/scores/ascendancy-challenges'
import { Route as EventsEventIdRouteImport } from './routes/events/$eventId'
import { Route as AdminUserManagementRouteImport } from './routes/admin/user-management'
import { Route as AdminTimingsRouteImport } from './routes/admin/timings'
import { Route as AdminTeamSuggestionsRouteImport } from './routes/admin/team-suggestions'
import { Route as AdminTeamSortRouteImport } from './routes/admin/team-sort'
import { Route as AdminSubmissionsRouteImport } from './routes/admin/submissions'
import { Route as AdminRecurringJobsRouteImport } from './routes/admin/recurring-jobs'
import { Route as AdminActivityRouteImport } from './routes/admin/activity'
import { Route as TeamStashesRouteRouteImport } from './routes/team/stashes/route'
import { Route as ProfileUserIdRouteRouteImport } from './routes/profile/$userId/route'
import { Route as AdminGuildIndexRouteImport } from './routes/admin/guild/index'
import { Route as AdminEventsIndexRouteImport } from './routes/admin/events/index'
import { Route as TeamStashesStashIdRouteImport } from './routes/team/stashes/$stashId'
import { Route as AuthTwitchCallbackRouteImport } from './routes/auth/twitch.callback'
import { Route as AuthPoeCallbackRouteImport } from './routes/auth/poe.callback'
import { Route as AuthDiscordCallbackRouteImport } from './routes/auth/discord.callback'
import { Route as AdminGuildStashesRouteRouteImport } from './routes/admin/guild/stashes/route'
import { Route as AdminGuildLogsRouteRouteImport } from './routes/admin/guild/logs/route'
import { Route as ProfileUserIdEventIdCharacterIdRouteImport } from './routes/profile/$userId/$eventId.$characterId'
import { Route as AdminGuildStashesStashIdRouteImport } from './routes/admin/guild/stashes/$stashId'
import { Route as AdminGuildLogsGuildIdRouteImport } from './routes/admin/guild/logs/$guildId'
import { Route as AdminEventsEventIdUnvalidatedObjectivesRouteImport } from './routes/admin/events/$eventId/unvalidated-objectives'
import { Route as AdminEventsEventIdTeamsRouteImport } from './routes/admin/events/$eventId/teams'
import { Route as AdminEventsEventIdScoringPresetsRouteImport } from './routes/admin/events/$eventId/scoring-presets'
import { Route as AdminEventsEventIdObjectivesObjectiveIdRouteImport } from './routes/admin/events/$eventId/objectives.$objectiveId'

const SubmissionsRoute = SubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRouteRoute = TeamRouteRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamsRouteRoute = StreamsRouteRouteImport.update({
  id: '/streams',
  path: '/streams',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoresRouteRoute = ScoresRouteRouteImport.update({
  id: '/scores',
  path: '/scores',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamWishlistRoute = TeamWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => TeamRouteRoute,
} as any)
const TeamAtlasRoute = TeamAtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => TeamRouteRoute,
} as any)
const StreamsTwitchAccountRoute = StreamsTwitchAccountRouteImport.update({
  id: '/$twitchAccount',
  path: '/$twitchAccount',
  getParentRoute: () => StreamsRouteRoute,
} as any)
const ScoresUniquesRoute = ScoresUniquesRouteImport.update({
  id: '/uniques',
  path: '/uniques',
  getParentRoute: () => ScoresRouteRoute,
} as any)
const ScoresSlotUniquesRoute = ScoresSlotUniquesRouteImport.update({
  id: '/slot-uniques',
  path: '/slot-uniques',
  getParentRoute: () => ScoresRouteRoute,
} as any)
const ScoresScarabsRoute = ScoresScarabsRouteImport.update({
  id: '/scarabs',
  path: '/scarabs',
  getParentRoute: () => ScoresRouteRoute,
} as any)
const ScoresRacesRoute = ScoresRacesRouteImport.update({
  id: '/races',
  path: '/races',
  getParentRoute: () => ScoresRouteRoute,
} as any)
const ScoresProgressRoute = ScoresProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => ScoresRouteRoute,
} as any)
const ScoresLadderRoute = ScoresLadderRouteImport.update({
  id: '/ladder',
  path: '/ladder',
  getParentRoute: () => ScoresRouteRoute,
} as any)
const ScoresHeistRoute = ScoresHeistRouteImport.update({
  id: '/heist',
  path: '/heist',
  getParentRoute: () => ScoresRouteRoute,
} as any)
const ScoresGraftRaceRoute = ScoresGraftRaceRouteImport.update({
  id: '/graft-race',
  path: '/graft-race',
  getParentRoute: () => ScoresRouteRoute,
} as any)
const ScoresGemsRoute = ScoresGemsRouteImport.update({
  id: '/gems',
  path: '/gems',
  getParentRoute: () => ScoresRouteRoute,
} as any)
const ScoresFoulbornUniquesRoute = ScoresFoulbornUniquesRouteImport.update({
  id: '/foulborn-uniques',
  path: '/foulborn-uniques',
  getParentRoute: () => ScoresRouteRoute,
} as any)
const ScoresForYouRoute = ScoresForYouRouteImport.update({
  id: '/for-you',
  path: '/for-you',
  getParentRoute: () => ScoresRouteRoute,
} as any)
const ScoresFocusUniquesRoute = ScoresFocusUniquesRouteImport.update({
  id: '/focus-uniques',
  path: '/focus-uniques',
  getParentRoute: () => ScoresRouteRoute,
} as any)
const ScoresDelveRoute = ScoresDelveRouteImport.update({
  id: '/delve',
  path: '/delve',
  getParentRoute: () => ScoresRouteRoute,
} as any)
const ScoresDailiesRoute = ScoresDailiesRouteImport.update({
  id: '/dailies',
  path: '/dailies',
  getParentRoute: () => ScoresRouteRoute,
} as any)
const ScoresCollectionsRoute = ScoresCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => ScoresRouteRoute,
} as any)
const ScoresBountiesRoute = ScoresBountiesRouteImport.update({
  id: '/bounties',
  path: '/bounties',
  getParentRoute: () => ScoresRouteRoute,
} as any)
const ScoresBingoRoute = ScoresBingoRouteImport.update({
  id: '/bingo',
  path: '/bingo',
  getParentRoute: () => ScoresRouteRoute,
} as any)
const ScoresAscendancyChallengesRoute =
  ScoresAscendancyChallengesRouteImport.update({
    id: '/ascendancy-challenges',
    path: '/ascendancy-challenges',
    getParentRoute: () => ScoresRouteRoute,
  } as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUserManagementRoute = AdminUserManagementRouteImport.update({
  id: '/admin/user-management',
  path: '/admin/user-management',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTimingsRoute = AdminTimingsRouteImport.update({
  id: '/admin/timings',
  path: '/admin/timings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamSuggestionsRoute = AdminTeamSuggestionsRouteImport.update({
  id: '/admin/team-suggestions',
  path: '/admin/team-suggestions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamSortRoute = AdminTeamSortRouteImport.update({
  id: '/admin/team-sort',
  path: '/admin/team-sort',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/admin/submissions',
  path: '/admin/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRecurringJobsRoute = AdminRecurringJobsRouteImport.update({
  id: '/admin/recurring-jobs',
  path: '/admin/recurring-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/admin/activity',
  path: '/admin/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamStashesRouteRoute = TeamStashesRouteRouteImport.update({
  id: '/stashes',
  path: '/stashes',
  getParentRoute: () => TeamRouteRoute,
} as any)
const ProfileUserIdRouteRoute = ProfileUserIdRouteRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGuildIndexRoute = AdminGuildIndexRouteImport.update({
  id: '/admin/guild/',
  path: '/admin/guild/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsIndexRoute = AdminEventsIndexRouteImport.update({
  id: '/admin/events/',
  path: '/admin/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamStashesStashIdRoute = TeamStashesStashIdRouteImport.update({
  id: '/$stashId',
  path: '/$stashId',
  getParentRoute: () => TeamStashesRouteRoute,
} as any)
const AuthTwitchCallbackRoute = AuthTwitchCallbackRouteImport.update({
  id: '/auth/twitch/callback',
  path: '/auth/twitch/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPoeCallbackRoute = AuthPoeCallbackRouteImport.update({
  id: '/auth/poe/callback',
  path: '/auth/poe/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDiscordCallbackRoute = AuthDiscordCallbackRouteImport.update({
  id: '/auth/discord/callback',
  path: '/auth/discord/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGuildStashesRouteRoute = AdminGuildStashesRouteRouteImport.update({
  id: '/admin/guild/stashes',
  path: '/admin/guild/stashes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGuildLogsRouteRoute = AdminGuildLogsRouteRouteImport.update({
  id: '/admin/guild/logs',
  path: '/admin/guild/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdEventIdCharacterIdRoute =
  ProfileUserIdEventIdCharacterIdRouteImport.update({
    id: '/$eventId/$characterId',
    path: '/$eventId/$characterId',
    getParentRoute: () => ProfileUserIdRouteRoute,
  } as any)
const AdminGuildStashesStashIdRoute =
  AdminGuildStashesStashIdRouteImport.update({
    id: '/$stashId',
    path: '/$stashId',
    getParentRoute: () => AdminGuildStashesRouteRoute,
  } as any)
const AdminGuildLogsGuildIdRoute = AdminGuildLogsGuildIdRouteImport.update({
  id: '/$guildId',
  path: '/$guildId',
  getParentRoute: () => AdminGuildLogsRouteRoute,
} as any)
const AdminEventsEventIdUnvalidatedObjectivesRoute =
  AdminEventsEventIdUnvalidatedObjectivesRouteImport.update({
    id: '/admin/events/$eventId/unvalidated-objectives',
    path: '/admin/events/$eventId/unvalidated-objectives',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminEventsEventIdTeamsRoute = AdminEventsEventIdTeamsRouteImport.update({
  id: '/admin/events/$eventId/teams',
  path: '/admin/events/$eventId/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsEventIdScoringPresetsRoute =
  AdminEventsEventIdScoringPresetsRouteImport.update({
    id: '/admin/events/$eventId/scoring-presets',
    path: '/admin/events/$eventId/scoring-presets',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminEventsEventIdObjectivesObjectiveIdRoute =
  AdminEventsEventIdObjectivesObjectiveIdRouteImport.update({
    id: '/admin/events/$eventId/objectives/$objectiveId',
    path: '/admin/events/$eventId/objectives/$objectiveId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/scores': typeof ScoresRouteRouteWithChildren
  '/streams': typeof StreamsRouteRouteWithChildren
  '/team': typeof TeamRouteRouteWithChildren
  '/players': typeof PlayersRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/submissions': typeof SubmissionsRoute
  '/profile/$userId': typeof ProfileUserIdRouteRouteWithChildren
  '/team/stashes': typeof TeamStashesRouteRouteWithChildren
  '/admin/activity': typeof AdminActivityRoute
  '/admin/recurring-jobs': typeof AdminRecurringJobsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/team-sort': typeof AdminTeamSortRoute
  '/admin/team-suggestions': typeof AdminTeamSuggestionsRoute
  '/admin/timings': typeof AdminTimingsRoute
  '/admin/user-management': typeof AdminUserManagementRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/scores/ascendancy-challenges': typeof ScoresAscendancyChallengesRoute
  '/scores/bingo': typeof ScoresBingoRoute
  '/scores/bounties': typeof ScoresBountiesRoute
  '/scores/collections': typeof ScoresCollectionsRoute
  '/scores/dailies': typeof ScoresDailiesRoute
  '/scores/delve': typeof ScoresDelveRoute
  '/scores/focus-uniques': typeof ScoresFocusUniquesRoute
  '/scores/for-you': typeof ScoresForYouRoute
  '/scores/foulborn-uniques': typeof ScoresFoulbornUniquesRoute
  '/scores/gems': typeof ScoresGemsRoute
  '/scores/graft-race': typeof ScoresGraftRaceRoute
  '/scores/heist': typeof ScoresHeistRoute
  '/scores/ladder': typeof ScoresLadderRoute
  '/scores/progress': typeof ScoresProgressRoute
  '/scores/races': typeof ScoresRacesRoute
  '/scores/scarabs': typeof ScoresScarabsRoute
  '/scores/slot-uniques': typeof ScoresSlotUniquesRoute
  '/scores/uniques': typeof ScoresUniquesRoute
  '/streams/$twitchAccount': typeof StreamsTwitchAccountRoute
  '/team/atlas': typeof TeamAtlasRoute
  '/team/wishlist': typeof TeamWishlistRoute
  '/admin/': typeof AdminIndexRoute
  '/events/': typeof EventsIndexRoute
  '/admin/guild/logs': typeof AdminGuildLogsRouteRouteWithChildren
  '/admin/guild/stashes': typeof AdminGuildStashesRouteRouteWithChildren
  '/auth/discord/callback': typeof AuthDiscordCallbackRoute
  '/auth/poe/callback': typeof AuthPoeCallbackRoute
  '/auth/twitch/callback': typeof AuthTwitchCallbackRoute
  '/team/stashes/$stashId': typeof TeamStashesStashIdRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/admin/guild/': typeof AdminGuildIndexRoute
  '/admin/events/$eventId/scoring-presets': typeof AdminEventsEventIdScoringPresetsRoute
  '/admin/events/$eventId/teams': typeof AdminEventsEventIdTeamsRoute
  '/admin/events/$eventId/unvalidated-objectives': typeof AdminEventsEventIdUnvalidatedObjectivesRoute
  '/admin/guild/logs/$guildId': typeof AdminGuildLogsGuildIdRoute
  '/admin/guild/stashes/$stashId': typeof AdminGuildStashesStashIdRoute
  '/profile/$userId/$eventId/$characterId': typeof ProfileUserIdEventIdCharacterIdRoute
  '/admin/events/$eventId/objectives/$objectiveId': typeof AdminEventsEventIdObjectivesObjectiveIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/scores': typeof ScoresRouteRouteWithChildren
  '/streams': typeof StreamsRouteRouteWithChildren
  '/team': typeof TeamRouteRouteWithChildren
  '/players': typeof PlayersRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/submissions': typeof SubmissionsRoute
  '/profile/$userId': typeof ProfileUserIdRouteRouteWithChildren
  '/team/stashes': typeof TeamStashesRouteRouteWithChildren
  '/admin/activity': typeof AdminActivityRoute
  '/admin/recurring-jobs': typeof AdminRecurringJobsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/team-sort': typeof AdminTeamSortRoute
  '/admin/team-suggestions': typeof AdminTeamSuggestionsRoute
  '/admin/timings': typeof AdminTimingsRoute
  '/admin/user-management': typeof AdminUserManagementRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/scores/ascendancy-challenges': typeof ScoresAscendancyChallengesRoute
  '/scores/bingo': typeof ScoresBingoRoute
  '/scores/bounties': typeof ScoresBountiesRoute
  '/scores/collections': typeof ScoresCollectionsRoute
  '/scores/dailies': typeof ScoresDailiesRoute
  '/scores/delve': typeof ScoresDelveRoute
  '/scores/focus-uniques': typeof ScoresFocusUniquesRoute
  '/scores/for-you': typeof ScoresForYouRoute
  '/scores/foulborn-uniques': typeof ScoresFoulbornUniquesRoute
  '/scores/gems': typeof ScoresGemsRoute
  '/scores/graft-race': typeof ScoresGraftRaceRoute
  '/scores/heist': typeof ScoresHeistRoute
  '/scores/ladder': typeof ScoresLadderRoute
  '/scores/progress': typeof ScoresProgressRoute
  '/scores/races': typeof ScoresRacesRoute
  '/scores/scarabs': typeof ScoresScarabsRoute
  '/scores/slot-uniques': typeof ScoresSlotUniquesRoute
  '/scores/uniques': typeof ScoresUniquesRoute
  '/streams/$twitchAccount': typeof StreamsTwitchAccountRoute
  '/team/atlas': typeof TeamAtlasRoute
  '/team/wishlist': typeof TeamWishlistRoute
  '/admin': typeof AdminIndexRoute
  '/events': typeof EventsIndexRoute
  '/admin/guild/logs': typeof AdminGuildLogsRouteRouteWithChildren
  '/admin/guild/stashes': typeof AdminGuildStashesRouteRouteWithChildren
  '/auth/discord/callback': typeof AuthDiscordCallbackRoute
  '/auth/poe/callback': typeof AuthPoeCallbackRoute
  '/auth/twitch/callback': typeof AuthTwitchCallbackRoute
  '/team/stashes/$stashId': typeof TeamStashesStashIdRoute
  '/admin/events': typeof AdminEventsIndexRoute
  '/admin/guild': typeof AdminGuildIndexRoute
  '/admin/events/$eventId/scoring-presets': typeof AdminEventsEventIdScoringPresetsRoute
  '/admin/events/$eventId/teams': typeof AdminEventsEventIdTeamsRoute
  '/admin/events/$eventId/unvalidated-objectives': typeof AdminEventsEventIdUnvalidatedObjectivesRoute
  '/admin/guild/logs/$guildId': typeof AdminGuildLogsGuildIdRoute
  '/admin/guild/stashes/$stashId': typeof AdminGuildStashesStashIdRoute
  '/profile/$userId/$eventId/$characterId': typeof ProfileUserIdEventIdCharacterIdRoute
  '/admin/events/$eventId/objectives/$objectiveId': typeof AdminEventsEventIdObjectivesObjectiveIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/scores': typeof ScoresRouteRouteWithChildren
  '/streams': typeof StreamsRouteRouteWithChildren
  '/team': typeof TeamRouteRouteWithChildren
  '/players': typeof PlayersRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/submissions': typeof SubmissionsRoute
  '/profile/$userId': typeof ProfileUserIdRouteRouteWithChildren
  '/team/stashes': typeof TeamStashesRouteRouteWithChildren
  '/admin/activity': typeof AdminActivityRoute
  '/admin/recurring-jobs': typeof AdminRecurringJobsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/team-sort': typeof AdminTeamSortRoute
  '/admin/team-suggestions': typeof AdminTeamSuggestionsRoute
  '/admin/timings': typeof AdminTimingsRoute
  '/admin/user-management': typeof AdminUserManagementRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/scores/ascendancy-challenges': typeof ScoresAscendancyChallengesRoute
  '/scores/bingo': typeof ScoresBingoRoute
  '/scores/bounties': typeof ScoresBountiesRoute
  '/scores/collections': typeof ScoresCollectionsRoute
  '/scores/dailies': typeof ScoresDailiesRoute
  '/scores/delve': typeof ScoresDelveRoute
  '/scores/focus-uniques': typeof ScoresFocusUniquesRoute
  '/scores/for-you': typeof ScoresForYouRoute
  '/scores/foulborn-uniques': typeof ScoresFoulbornUniquesRoute
  '/scores/gems': typeof ScoresGemsRoute
  '/scores/graft-race': typeof ScoresGraftRaceRoute
  '/scores/heist': typeof ScoresHeistRoute
  '/scores/ladder': typeof ScoresLadderRoute
  '/scores/progress': typeof ScoresProgressRoute
  '/scores/races': typeof ScoresRacesRoute
  '/scores/scarabs': typeof ScoresScarabsRoute
  '/scores/slot-uniques': typeof ScoresSlotUniquesRoute
  '/scores/uniques': typeof ScoresUniquesRoute
  '/streams/$twitchAccount': typeof StreamsTwitchAccountRoute
  '/team/atlas': typeof TeamAtlasRoute
  '/team/wishlist': typeof TeamWishlistRoute
  '/admin/': typeof AdminIndexRoute
  '/events/': typeof EventsIndexRoute
  '/admin/guild/logs': typeof AdminGuildLogsRouteRouteWithChildren
  '/admin/guild/stashes': typeof AdminGuildStashesRouteRouteWithChildren
  '/auth/discord/callback': typeof AuthDiscordCallbackRoute
  '/auth/poe/callback': typeof AuthPoeCallbackRoute
  '/auth/twitch/callback': typeof AuthTwitchCallbackRoute
  '/team/stashes/$stashId': typeof TeamStashesStashIdRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/admin/guild/': typeof AdminGuildIndexRoute
  '/admin/events/$eventId/scoring-presets': typeof AdminEventsEventIdScoringPresetsRoute
  '/admin/events/$eventId/teams': typeof AdminEventsEventIdTeamsRoute
  '/admin/events/$eventId/unvalidated-objectives': typeof AdminEventsEventIdUnvalidatedObjectivesRoute
  '/admin/guild/logs/$guildId': typeof AdminGuildLogsGuildIdRoute
  '/admin/guild/stashes/$stashId': typeof AdminGuildStashesStashIdRoute
  '/profile/$userId/$eventId/$characterId': typeof ProfileUserIdEventIdCharacterIdRoute
  '/admin/events/$eventId/objectives/$objectiveId': typeof AdminEventsEventIdObjectivesObjectiveIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/scores'
    | '/streams'
    | '/team'
    | '/players'
    | '/rules'
    | '/settings'
    | '/submissions'
    | '/profile/$userId'
    | '/team/stashes'
    | '/admin/activity'
    | '/admin/recurring-jobs'
    | '/admin/submissions'
    | '/admin/team-sort'
    | '/admin/team-suggestions'
    | '/admin/timings'
    | '/admin/user-management'
    | '/events/$eventId'
    | '/scores/ascendancy-challenges'
    | '/scores/bingo'
    | '/scores/bounties'
    | '/scores/collections'
    | '/scores/dailies'
    | '/scores/delve'
    | '/scores/focus-uniques'
    | '/scores/for-you'
    | '/scores/foulborn-uniques'
    | '/scores/gems'
    | '/scores/graft-race'
    | '/scores/heist'
    | '/scores/ladder'
    | '/scores/progress'
    | '/scores/races'
    | '/scores/scarabs'
    | '/scores/slot-uniques'
    | '/scores/uniques'
    | '/streams/$twitchAccount'
    | '/team/atlas'
    | '/team/wishlist'
    | '/admin/'
    | '/events/'
    | '/admin/guild/logs'
    | '/admin/guild/stashes'
    | '/auth/discord/callback'
    | '/auth/poe/callback'
    | '/auth/twitch/callback'
    | '/team/stashes/$stashId'
    | '/admin/events/'
    | '/admin/guild/'
    | '/admin/events/$eventId/scoring-presets'
    | '/admin/events/$eventId/teams'
    | '/admin/events/$eventId/unvalidated-objectives'
    | '/admin/guild/logs/$guildId'
    | '/admin/guild/stashes/$stashId'
    | '/profile/$userId/$eventId/$characterId'
    | '/admin/events/$eventId/objectives/$objectiveId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/scores'
    | '/streams'
    | '/team'
    | '/players'
    | '/rules'
    | '/settings'
    | '/submissions'
    | '/profile/$userId'
    | '/team/stashes'
    | '/admin/activity'
    | '/admin/recurring-jobs'
    | '/admin/submissions'
    | '/admin/team-sort'
    | '/admin/team-suggestions'
    | '/admin/timings'
    | '/admin/user-management'
    | '/events/$eventId'
    | '/scores/ascendancy-challenges'
    | '/scores/bingo'
    | '/scores/bounties'
    | '/scores/collections'
    | '/scores/dailies'
    | '/scores/delve'
    | '/scores/focus-uniques'
    | '/scores/for-you'
    | '/scores/foulborn-uniques'
    | '/scores/gems'
    | '/scores/graft-race'
    | '/scores/heist'
    | '/scores/ladder'
    | '/scores/progress'
    | '/scores/races'
    | '/scores/scarabs'
    | '/scores/slot-uniques'
    | '/scores/uniques'
    | '/streams/$twitchAccount'
    | '/team/atlas'
    | '/team/wishlist'
    | '/admin'
    | '/events'
    | '/admin/guild/logs'
    | '/admin/guild/stashes'
    | '/auth/discord/callback'
    | '/auth/poe/callback'
    | '/auth/twitch/callback'
    | '/team/stashes/$stashId'
    | '/admin/events'
    | '/admin/guild'
    | '/admin/events/$eventId/scoring-presets'
    | '/admin/events/$eventId/teams'
    | '/admin/events/$eventId/unvalidated-objectives'
    | '/admin/guild/logs/$guildId'
    | '/admin/guild/stashes/$stashId'
    | '/profile/$userId/$eventId/$characterId'
    | '/admin/events/$eventId/objectives/$objectiveId'
  id:
    | '__root__'
    | '/'
    | '/scores'
    | '/streams'
    | '/team'
    | '/players'
    | '/rules'
    | '/settings'
    | '/submissions'
    | '/profile/$userId'
    | '/team/stashes'
    | '/admin/activity'
    | '/admin/recurring-jobs'
    | '/admin/submissions'
    | '/admin/team-sort'
    | '/admin/team-suggestions'
    | '/admin/timings'
    | '/admin/user-management'
    | '/events/$eventId'
    | '/scores/ascendancy-challenges'
    | '/scores/bingo'
    | '/scores/bounties'
    | '/scores/collections'
    | '/scores/dailies'
    | '/scores/delve'
    | '/scores/focus-uniques'
    | '/scores/for-you'
    | '/scores/foulborn-uniques'
    | '/scores/gems'
    | '/scores/graft-race'
    | '/scores/heist'
    | '/scores/ladder'
    | '/scores/progress'
    | '/scores/races'
    | '/scores/scarabs'
    | '/scores/slot-uniques'
    | '/scores/uniques'
    | '/streams/$twitchAccount'
    | '/team/atlas'
    | '/team/wishlist'
    | '/admin/'
    | '/events/'
    | '/admin/guild/logs'
    | '/admin/guild/stashes'
    | '/auth/discord/callback'
    | '/auth/poe/callback'
    | '/auth/twitch/callback'
    | '/team/stashes/$stashId'
    | '/admin/events/'
    | '/admin/guild/'
    | '/admin/events/$eventId/scoring-presets'
    | '/admin/events/$eventId/teams'
    | '/admin/events/$eventId/unvalidated-objectives'
    | '/admin/guild/logs/$guildId'
    | '/admin/guild/stashes/$stashId'
    | '/profile/$userId/$eventId/$characterId'
    | '/admin/events/$eventId/objectives/$objectiveId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ScoresRouteRoute: typeof ScoresRouteRouteWithChildren
  StreamsRouteRoute: typeof StreamsRouteRouteWithChildren
  TeamRouteRoute: typeof TeamRouteRouteWithChildren
  PlayersRoute: typeof PlayersRoute
  RulesRoute: typeof RulesRoute
  SettingsRoute: typeof SettingsRoute
  SubmissionsRoute: typeof SubmissionsRoute
  ProfileUserIdRouteRoute: typeof ProfileUserIdRouteRouteWithChildren
  AdminActivityRoute: typeof AdminActivityRoute
  AdminRecurringJobsRoute: typeof AdminRecurringJobsRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
  AdminTeamSortRoute: typeof AdminTeamSortRoute
  AdminTeamSuggestionsRoute: typeof AdminTeamSuggestionsRoute
  AdminTimingsRoute: typeof AdminTimingsRoute
  AdminUserManagementRoute: typeof AdminUserManagementRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  AdminGuildLogsRouteRoute: typeof AdminGuildLogsRouteRouteWithChildren
  AdminGuildStashesRouteRoute: typeof AdminGuildStashesRouteRouteWithChildren
  AuthDiscordCallbackRoute: typeof AuthDiscordCallbackRoute
  AuthPoeCallbackRoute: typeof AuthPoeCallbackRoute
  AuthTwitchCallbackRoute: typeof AuthTwitchCallbackRoute
  AdminEventsIndexRoute: typeof AdminEventsIndexRoute
  AdminGuildIndexRoute: typeof AdminGuildIndexRoute
  AdminEventsEventIdScoringPresetsRoute: typeof AdminEventsEventIdScoringPresetsRoute
  AdminEventsEventIdTeamsRoute: typeof AdminEventsEventIdTeamsRoute
  AdminEventsEventIdUnvalidatedObjectivesRoute: typeof AdminEventsEventIdUnvalidatedObjectivesRoute
  AdminEventsEventIdObjectivesObjectiveIdRoute: typeof AdminEventsEventIdObjectivesObjectiveIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submissions': {
      id: '/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof SubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streams': {
      id: '/streams'
      path: '/streams'
      fullPath: '/streams'
      preLoaderRoute: typeof StreamsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scores': {
      id: '/scores'
      path: '/scores'
      fullPath: '/scores'
      preLoaderRoute: typeof ScoresRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/wishlist': {
      id: '/team/wishlist'
      path: '/wishlist'
      fullPath: '/team/wishlist'
      preLoaderRoute: typeof TeamWishlistRouteImport
      parentRoute: typeof TeamRouteRoute
    }
    '/team/atlas': {
      id: '/team/atlas'
      path: '/atlas'
      fullPath: '/team/atlas'
      preLoaderRoute: typeof TeamAtlasRouteImport
      parentRoute: typeof TeamRouteRoute
    }
    '/streams/$twitchAccount': {
      id: '/streams/$twitchAccount'
      path: '/$twitchAccount'
      fullPath: '/streams/$twitchAccount'
      preLoaderRoute: typeof StreamsTwitchAccountRouteImport
      parentRoute: typeof StreamsRouteRoute
    }
    '/scores/uniques': {
      id: '/scores/uniques'
      path: '/uniques'
      fullPath: '/scores/uniques'
      preLoaderRoute: typeof ScoresUniquesRouteImport
      parentRoute: typeof ScoresRouteRoute
    }
    '/scores/slot-uniques': {
      id: '/scores/slot-uniques'
      path: '/slot-uniques'
      fullPath: '/scores/slot-uniques'
      preLoaderRoute: typeof ScoresSlotUniquesRouteImport
      parentRoute: typeof ScoresRouteRoute
    }
    '/scores/scarabs': {
      id: '/scores/scarabs'
      path: '/scarabs'
      fullPath: '/scores/scarabs'
      preLoaderRoute: typeof ScoresScarabsRouteImport
      parentRoute: typeof ScoresRouteRoute
    }
    '/scores/races': {
      id: '/scores/races'
      path: '/races'
      fullPath: '/scores/races'
      preLoaderRoute: typeof ScoresRacesRouteImport
      parentRoute: typeof ScoresRouteRoute
    }
    '/scores/progress': {
      id: '/scores/progress'
      path: '/progress'
      fullPath: '/scores/progress'
      preLoaderRoute: typeof ScoresProgressRouteImport
      parentRoute: typeof ScoresRouteRoute
    }
    '/scores/ladder': {
      id: '/scores/ladder'
      path: '/ladder'
      fullPath: '/scores/ladder'
      preLoaderRoute: typeof ScoresLadderRouteImport
      parentRoute: typeof ScoresRouteRoute
    }
    '/scores/heist': {
      id: '/scores/heist'
      path: '/heist'
      fullPath: '/scores/heist'
      preLoaderRoute: typeof ScoresHeistRouteImport
      parentRoute: typeof ScoresRouteRoute
    }
    '/scores/graft-race': {
      id: '/scores/graft-race'
      path: '/graft-race'
      fullPath: '/scores/graft-race'
      preLoaderRoute: typeof ScoresGraftRaceRouteImport
      parentRoute: typeof ScoresRouteRoute
    }
    '/scores/gems': {
      id: '/scores/gems'
      path: '/gems'
      fullPath: '/scores/gems'
      preLoaderRoute: typeof ScoresGemsRouteImport
      parentRoute: typeof ScoresRouteRoute
    }
    '/scores/foulborn-uniques': {
      id: '/scores/foulborn-uniques'
      path: '/foulborn-uniques'
      fullPath: '/scores/foulborn-uniques'
      preLoaderRoute: typeof ScoresFoulbornUniquesRouteImport
      parentRoute: typeof ScoresRouteRoute
    }
    '/scores/for-you': {
      id: '/scores/for-you'
      path: '/for-you'
      fullPath: '/scores/for-you'
      preLoaderRoute: typeof ScoresForYouRouteImport
      parentRoute: typeof ScoresRouteRoute
    }
    '/scores/focus-uniques': {
      id: '/scores/focus-uniques'
      path: '/focus-uniques'
      fullPath: '/scores/focus-uniques'
      preLoaderRoute: typeof ScoresFocusUniquesRouteImport
      parentRoute: typeof ScoresRouteRoute
    }
    '/scores/delve': {
      id: '/scores/delve'
      path: '/delve'
      fullPath: '/scores/delve'
      preLoaderRoute: typeof ScoresDelveRouteImport
      parentRoute: typeof ScoresRouteRoute
    }
    '/scores/dailies': {
      id: '/scores/dailies'
      path: '/dailies'
      fullPath: '/scores/dailies'
      preLoaderRoute: typeof ScoresDailiesRouteImport
      parentRoute: typeof ScoresRouteRoute
    }
    '/scores/collections': {
      id: '/scores/collections'
      path: '/collections'
      fullPath: '/scores/collections'
      preLoaderRoute: typeof ScoresCollectionsRouteImport
      parentRoute: typeof ScoresRouteRoute
    }
    '/scores/bounties': {
      id: '/scores/bounties'
      path: '/bounties'
      fullPath: '/scores/bounties'
      preLoaderRoute: typeof ScoresBountiesRouteImport
      parentRoute: typeof ScoresRouteRoute
    }
    '/scores/bingo': {
      id: '/scores/bingo'
      path: '/bingo'
      fullPath: '/scores/bingo'
      preLoaderRoute: typeof ScoresBingoRouteImport
      parentRoute: typeof ScoresRouteRoute
    }
    '/scores/ascendancy-challenges': {
      id: '/scores/ascendancy-challenges'
      path: '/ascendancy-challenges'
      fullPath: '/scores/ascendancy-challenges'
      preLoaderRoute: typeof ScoresAscendancyChallengesRouteImport
      parentRoute: typeof ScoresRouteRoute
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/user-management': {
      id: '/admin/user-management'
      path: '/admin/user-management'
      fullPath: '/admin/user-management'
      preLoaderRoute: typeof AdminUserManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/timings': {
      id: '/admin/timings'
      path: '/admin/timings'
      fullPath: '/admin/timings'
      preLoaderRoute: typeof AdminTimingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/team-suggestions': {
      id: '/admin/team-suggestions'
      path: '/admin/team-suggestions'
      fullPath: '/admin/team-suggestions'
      preLoaderRoute: typeof AdminTeamSuggestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/team-sort': {
      id: '/admin/team-sort'
      path: '/admin/team-sort'
      fullPath: '/admin/team-sort'
      preLoaderRoute: typeof AdminTeamSortRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/admin/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/recurring-jobs': {
      id: '/admin/recurring-jobs'
      path: '/admin/recurring-jobs'
      fullPath: '/admin/recurring-jobs'
      preLoaderRoute: typeof AdminRecurringJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/admin/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/stashes': {
      id: '/team/stashes'
      path: '/stashes'
      fullPath: '/team/stashes'
      preLoaderRoute: typeof TeamStashesRouteRouteImport
      parentRoute: typeof TeamRouteRoute
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/guild/': {
      id: '/admin/guild/'
      path: '/admin/guild'
      fullPath: '/admin/guild/'
      preLoaderRoute: typeof AdminGuildIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/': {
      id: '/admin/events/'
      path: '/admin/events'
      fullPath: '/admin/events/'
      preLoaderRoute: typeof AdminEventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/stashes/$stashId': {
      id: '/team/stashes/$stashId'
      path: '/$stashId'
      fullPath: '/team/stashes/$stashId'
      preLoaderRoute: typeof TeamStashesStashIdRouteImport
      parentRoute: typeof TeamStashesRouteRoute
    }
    '/auth/twitch/callback': {
      id: '/auth/twitch/callback'
      path: '/auth/twitch/callback'
      fullPath: '/auth/twitch/callback'
      preLoaderRoute: typeof AuthTwitchCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/poe/callback': {
      id: '/auth/poe/callback'
      path: '/auth/poe/callback'
      fullPath: '/auth/poe/callback'
      preLoaderRoute: typeof AuthPoeCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/discord/callback': {
      id: '/auth/discord/callback'
      path: '/auth/discord/callback'
      fullPath: '/auth/discord/callback'
      preLoaderRoute: typeof AuthDiscordCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/guild/stashes': {
      id: '/admin/guild/stashes'
      path: '/admin/guild/stashes'
      fullPath: '/admin/guild/stashes'
      preLoaderRoute: typeof AdminGuildStashesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/guild/logs': {
      id: '/admin/guild/logs'
      path: '/admin/guild/logs'
      fullPath: '/admin/guild/logs'
      preLoaderRoute: typeof AdminGuildLogsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId/$eventId/$characterId': {
      id: '/profile/$userId/$eventId/$characterId'
      path: '/$eventId/$characterId'
      fullPath: '/profile/$userId/$eventId/$characterId'
      preLoaderRoute: typeof ProfileUserIdEventIdCharacterIdRouteImport
      parentRoute: typeof ProfileUserIdRouteRoute
    }
    '/admin/guild/stashes/$stashId': {
      id: '/admin/guild/stashes/$stashId'
      path: '/$stashId'
      fullPath: '/admin/guild/stashes/$stashId'
      preLoaderRoute: typeof AdminGuildStashesStashIdRouteImport
      parentRoute: typeof AdminGuildStashesRouteRoute
    }
    '/admin/guild/logs/$guildId': {
      id: '/admin/guild/logs/$guildId'
      path: '/$guildId'
      fullPath: '/admin/guild/logs/$guildId'
      preLoaderRoute: typeof AdminGuildLogsGuildIdRouteImport
      parentRoute: typeof AdminGuildLogsRouteRoute
    }
    '/admin/events/$eventId/unvalidated-objectives': {
      id: '/admin/events/$eventId/unvalidated-objectives'
      path: '/admin/events/$eventId/unvalidated-objectives'
      fullPath: '/admin/events/$eventId/unvalidated-objectives'
      preLoaderRoute: typeof AdminEventsEventIdUnvalidatedObjectivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/$eventId/teams': {
      id: '/admin/events/$eventId/teams'
      path: '/admin/events/$eventId/teams'
      fullPath: '/admin/events/$eventId/teams'
      preLoaderRoute: typeof AdminEventsEventIdTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/$eventId/scoring-presets': {
      id: '/admin/events/$eventId/scoring-presets'
      path: '/admin/events/$eventId/scoring-presets'
      fullPath: '/admin/events/$eventId/scoring-presets'
      preLoaderRoute: typeof AdminEventsEventIdScoringPresetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/$eventId/objectives/$objectiveId': {
      id: '/admin/events/$eventId/objectives/$objectiveId'
      path: '/admin/events/$eventId/objectives/$objectiveId'
      fullPath: '/admin/events/$eventId/objectives/$objectiveId'
      preLoaderRoute: typeof AdminEventsEventIdObjectivesObjectiveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ScoresRouteRouteChildren {
  ScoresAscendancyChallengesRoute: typeof ScoresAscendancyChallengesRoute
  ScoresBingoRoute: typeof ScoresBingoRoute
  ScoresBountiesRoute: typeof ScoresBountiesRoute
  ScoresCollectionsRoute: typeof ScoresCollectionsRoute
  ScoresDailiesRoute: typeof ScoresDailiesRoute
  ScoresDelveRoute: typeof ScoresDelveRoute
  ScoresFocusUniquesRoute: typeof ScoresFocusUniquesRoute
  ScoresForYouRoute: typeof ScoresForYouRoute
  ScoresFoulbornUniquesRoute: typeof ScoresFoulbornUniquesRoute
  ScoresGemsRoute: typeof ScoresGemsRoute
  ScoresGraftRaceRoute: typeof ScoresGraftRaceRoute
  ScoresHeistRoute: typeof ScoresHeistRoute
  ScoresLadderRoute: typeof ScoresLadderRoute
  ScoresProgressRoute: typeof ScoresProgressRoute
  ScoresRacesRoute: typeof ScoresRacesRoute
  ScoresScarabsRoute: typeof ScoresScarabsRoute
  ScoresSlotUniquesRoute: typeof ScoresSlotUniquesRoute
  ScoresUniquesRoute: typeof ScoresUniquesRoute
}

const ScoresRouteRouteChildren: ScoresRouteRouteChildren = {
  ScoresAscendancyChallengesRoute: ScoresAscendancyChallengesRoute,
  ScoresBingoRoute: ScoresBingoRoute,
  ScoresBountiesRoute: ScoresBountiesRoute,
  ScoresCollectionsRoute: ScoresCollectionsRoute,
  ScoresDailiesRoute: ScoresDailiesRoute,
  ScoresDelveRoute: ScoresDelveRoute,
  ScoresFocusUniquesRoute: ScoresFocusUniquesRoute,
  ScoresForYouRoute: ScoresForYouRoute,
  ScoresFoulbornUniquesRoute: ScoresFoulbornUniquesRoute,
  ScoresGemsRoute: ScoresGemsRoute,
  ScoresGraftRaceRoute: ScoresGraftRaceRoute,
  ScoresHeistRoute: ScoresHeistRoute,
  ScoresLadderRoute: ScoresLadderRoute,
  ScoresProgressRoute: ScoresProgressRoute,
  ScoresRacesRoute: ScoresRacesRoute,
  ScoresScarabsRoute: ScoresScarabsRoute,
  ScoresSlotUniquesRoute: ScoresSlotUniquesRoute,
  ScoresUniquesRoute: ScoresUniquesRoute,
}

const ScoresRouteRouteWithChildren = ScoresRouteRoute._addFileChildren(
  ScoresRouteRouteChildren,
)

interface StreamsRouteRouteChildren {
  StreamsTwitchAccountRoute: typeof StreamsTwitchAccountRoute
}

const StreamsRouteRouteChildren: StreamsRouteRouteChildren = {
  StreamsTwitchAccountRoute: StreamsTwitchAccountRoute,
}

const StreamsRouteRouteWithChildren = StreamsRouteRoute._addFileChildren(
  StreamsRouteRouteChildren,
)

interface TeamStashesRouteRouteChildren {
  TeamStashesStashIdRoute: typeof TeamStashesStashIdRoute
}

const TeamStashesRouteRouteChildren: TeamStashesRouteRouteChildren = {
  TeamStashesStashIdRoute: TeamStashesStashIdRoute,
}

const TeamStashesRouteRouteWithChildren =
  TeamStashesRouteRoute._addFileChildren(TeamStashesRouteRouteChildren)

interface TeamRouteRouteChildren {
  TeamStashesRouteRoute: typeof TeamStashesRouteRouteWithChildren
  TeamAtlasRoute: typeof TeamAtlasRoute
  TeamWishlistRoute: typeof TeamWishlistRoute
}

const TeamRouteRouteChildren: TeamRouteRouteChildren = {
  TeamStashesRouteRoute: TeamStashesRouteRouteWithChildren,
  TeamAtlasRoute: TeamAtlasRoute,
  TeamWishlistRoute: TeamWishlistRoute,
}

const TeamRouteRouteWithChildren = TeamRouteRoute._addFileChildren(
  TeamRouteRouteChildren,
)

interface ProfileUserIdRouteRouteChildren {
  ProfileUserIdEventIdCharacterIdRoute: typeof ProfileUserIdEventIdCharacterIdRoute
}

const ProfileUserIdRouteRouteChildren: ProfileUserIdRouteRouteChildren = {
  ProfileUserIdEventIdCharacterIdRoute: ProfileUserIdEventIdCharacterIdRoute,
}

const ProfileUserIdRouteRouteWithChildren =
  ProfileUserIdRouteRoute._addFileChildren(ProfileUserIdRouteRouteChildren)

interface AdminGuildLogsRouteRouteChildren {
  AdminGuildLogsGuildIdRoute: typeof AdminGuildLogsGuildIdRoute
}

const AdminGuildLogsRouteRouteChildren: AdminGuildLogsRouteRouteChildren = {
  AdminGuildLogsGuildIdRoute: AdminGuildLogsGuildIdRoute,
}

const AdminGuildLogsRouteRouteWithChildren =
  AdminGuildLogsRouteRoute._addFileChildren(AdminGuildLogsRouteRouteChildren)

interface AdminGuildStashesRouteRouteChildren {
  AdminGuildStashesStashIdRoute: typeof AdminGuildStashesStashIdRoute
}

const AdminGuildStashesRouteRouteChildren: AdminGuildStashesRouteRouteChildren =
  {
    AdminGuildStashesStashIdRoute: AdminGuildStashesStashIdRoute,
  }

const AdminGuildStashesRouteRouteWithChildren =
  AdminGuildStashesRouteRoute._addFileChildren(
    AdminGuildStashesRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ScoresRouteRoute: ScoresRouteRouteWithChildren,
  StreamsRouteRoute: StreamsRouteRouteWithChildren,
  TeamRouteRoute: TeamRouteRouteWithChildren,
  PlayersRoute: PlayersRoute,
  RulesRoute: RulesRoute,
  SettingsRoute: SettingsRoute,
  SubmissionsRoute: SubmissionsRoute,
  ProfileUserIdRouteRoute: ProfileUserIdRouteRouteWithChildren,
  AdminActivityRoute: AdminActivityRoute,
  AdminRecurringJobsRoute: AdminRecurringJobsRoute,
  AdminSubmissionsRoute: AdminSubmissionsRoute,
  AdminTeamSortRoute: AdminTeamSortRoute,
  AdminTeamSuggestionsRoute: AdminTeamSuggestionsRoute,
  AdminTimingsRoute: AdminTimingsRoute,
  AdminUserManagementRoute: AdminUserManagementRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  AdminGuildLogsRouteRoute: AdminGuildLogsRouteRouteWithChildren,
  AdminGuildStashesRouteRoute: AdminGuildStashesRouteRouteWithChildren,
  AuthDiscordCallbackRoute: AuthDiscordCallbackRoute,
  AuthPoeCallbackRoute: AuthPoeCallbackRoute,
  AuthTwitchCallbackRoute: AuthTwitchCallbackRoute,
  AdminEventsIndexRoute: AdminEventsIndexRoute,
  AdminGuildIndexRoute: AdminGuildIndexRoute,
  AdminEventsEventIdScoringPresetsRoute: AdminEventsEventIdScoringPresetsRoute,
  AdminEventsEventIdTeamsRoute: AdminEventsEventIdTeamsRoute,
  AdminEventsEventIdUnvalidatedObjectivesRoute:
    AdminEventsEventIdUnvalidatedObjectivesRoute,
  AdminEventsEventIdObjectivesObjectiveIdRoute:
    AdminEventsEventIdObjectivesObjectiveIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
