name: Deploy

on:
  push:
    branches:
      - main

env:
  IMAGE: ghcr.io/bpl-v2/frontend

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches

      - name: Get latest tag
        id: get_tag
        run: echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build --build-arg VITE_PUBLIC_BPL_BACKEND_URL=https://bpl-poe.com/api -t ${{ env.IMAGE }}:${{ steps.get_tag.outputs.tag }} .

      - name: Push Docker image
        run: |
          docker push ${{ env.IMAGE }}:${{ steps.get_tag.outputs.tag }}

      - name: Notify watchtower
        run: |
          curl -X POST "${{vars.SERVER_URL}}/watchtower/v1/update" -H "Authorization: Bearer ${{ secrets.WATCHTOWER_TOKEN }}"
