name: Deploy (Staging)

on:
  push:
    branches:
      - develop

env:
  IMAGE: ghcr.io/bpl-v2/frontend

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build \
            --build-arg VITE_PUBLIC_BPL_BACKEND_URL="${{ vars.STAGING_SERVER_URL }}/api" \
            -t ${{ env.IMAGE }}:sha-${{ github.sha }} .

      - name: Push Docker image
        run: docker push ${{ env.IMAGE }}:sha-${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Tag staging from build image
        run: |
          docker buildx imagetools create \
            --tag ${{ env.IMAGE }}:staging \
            ${{ env.IMAGE }}:sha-${{ github.sha }}

      - name: Notify watchtower on staging
        run: |
          curl -f -X POST "${{ vars.STAGING_SERVER_URL }}/watchtower/v1/update" \
            -H "Authorization: Bearer ${{ secrets.WATCHTOWER_STAGING_TOKEN }}"