// Sourced from RePoE's DefaultAltAscendancies.json passive tree
// (https://repoe-fork.github.io/passive_skill_trees/DefaultAltAscendancies.json),
// generated by fetch_alt_ascendancies.py - the nodes with
// is_ascendancy_starting_node: true whose id starts with
// "AlternateAscendancy" rather than the normal "Ascendancy" classes.
export const ALT_ASCENDANCIES: string[] = [
  "Aul Bloodline",
  "Necromantic",
  "Catarina Bloodline",
  "Warden of the Maji",
  "Nameless Bloodline",
  "Delirious",
  "Wildwood Primalist",
  "Farrul Bloodline",
  "Chaos Bloodline",
  "Lycia Bloodline",
  "Olroth Bloodline",
  "Oshabi Bloodline",
  "Warlock of the Mists",
  "Breachlord",
];
