// automatically generated by icon-generation/fetch_alt_ascendancies.py

export const ALT_ASCENDANCIES: string[] = [
  "Chaos",
  "Oshabi",
  "Nameless",
  "Catarina",
  "Aul",
  "Lycia",
  "Olroth",
  "Farrul",
  "Delirious",
  "Breachlord",
  "Saresh",
  "Velka",
  "Abyssal",
];
